### ISSUE TITLE
Add support for AWS IAM Identity Center (successor to AWS Single Sign-On) SSO credential format

### ISSUE THREAD

**Issue by tmldot** [aws/amazon-ec2-instance-selector#250]
We utilize AWS Identity Center Single Sign-On (SSO) enabled profiles, as outlined in the documentation at https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-files.html. Once I am authenticated to my SSO profile and have verified its authentication, the ec2-instance-selector script encounters a failure, as demonstrated below:

```
$ aws sso login --no-browser --sso-session my-login1

$ aws sts get-caller-identity --profile my-profile1
{
    "UserId": "AAAAAAAAAAAAAAAAAAAAA:user@mydomain.com",
    "Account": "0123456789012",
    "Arn": "arn:aws:sts::0123456789012:assumed-role/AWSReservedSSO_my-aws-role1_abababababababab/user@mydomain.com"
}

$ ec2-instance-selector --version
v2.4.1

$ ec2-instance-selector --memory 8 --vcpus 4 --cpu-architecture x86_64 -r us-east-1 -o table --profile my-profile1
panic: profile "my-profile1" is configured to use SSO but is missing required configuration: sso_region, sso_start_url

goroutine 1 [running]:
github.com/aws/aws-sdk-go/aws/session.Must(...)
	/go/pkg/mod/github.com/aws/aws-sdk-go@v1.44.59/aws/session/session.go:381
main.getRegionAndProfileAWSSession(0xe9b920?, 0xc00032b860)
	/amazon-ec2-instance-selector/cmd/main.go:507 +0x52a
main.main()
	/amazon-ec2-instance-selector/cmd/main.go:245 +0x1535
```

My sanitized .aws/config 
[sso-session my-login1
sso_start_url = https://mysite.awsapps.com/start
sso_region = us-east-1
sso_registration_scopes = sso:account:access

[profile my-profile1]
sso_session = my-login1
sso_account_id = 0123456789012
sso_role_name = my-aws-role1
region = us-east-1
output = json

**Comment by bwagner5** [comment]
hmmm I would have thought the AWS SDK for Go would have just picked this up. Let me research and see how this is supported in the SDK.

**Comment by bwagner5** [comment]
Apologies, this was fixed here but never released :( https://github.com/aws/amazon-ec2-instance-selector/commit/f6c1835fc59c31236d22ab31785a061f00bb3cb5 

Will release soon.

**Comment by karan-pingsafe** [comment]
when is this going to be released?

**Comment by yaakov-berkovitch** [comment]
@bwagner5 i still fail on same error. Does this fix already released ? If no, any ETA ? Thanks

**Comment by mentics** [comment]
I still get this error as well. However, I noticed the error is coming from the sdk, and not the code in this project. So, I downloaded this source, checked out tag v2.4.1 (because running the build from main didn't work for me), and then in go.mod, I updated the sdk version:
`github.com/aws/aws-sdk-go v1.51.28`
(that's the latest version), and then built and ran, and it worked.

There appears to be a [PR already for upgrading the sdk version](https://github.com/aws/amazon-ec2-instance-selector/pull/343) and I tested that version 1.50.35 and it also seemed to work.
